package com.ledcar01.controller;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * DMX-zone preset effect names, ids 1-210 plus 255 = auto-cycle. Extracted
 * from the vendor app's decompiled dmx_model resource array (not hand-typed)
 * to avoid transcription drift from the identical table already embedded in
 * LedCar01Simulator/Program.cs (DmxModeNames).
 */
public final class DmxModes {

    public static final Map<Integer, String> NAMES;

    static {
        Map<Integer, String> map = new LinkedHashMap<>();
        map.put(255, "Auto (cycle through effects)");
        map.put(1, "Forward Dreaming");
        map.put(2, "Backward Dreaming");
        map.put(3, "Forward 7 Colors");
        map.put(4, "Backward 7 Colors");
        map.put(5, "Forward RD/GN/BU");
        map.put(6, "Backward RD/GN/BU");
        map.put(7, "Forward YE/CN/VT");
        map.put(8, "Backward YE/CN/VT");
        map.put(9, "Forward 6 Colors RD");
        map.put(10, "Backward 6 Colors RD");
        map.put(11, "Forward 6 Colors GN");
        map.put(12, "Backward 6 Colors GN");
        map.put(13, "Forward 6 Colors BU");
        map.put(14, "Backward 6 Colors BU");
        map.put(15, "Forward 6 Colors CN");
        map.put(16, "Backward 6 Colors CN");
        map.put(17, "Forward 6 Colors YE");
        map.put(18, "Backward 6 Colors YE");
        map.put(19, "Forward 6 Colors VT");
        map.put(20, "Backward 6 Colors VT");
        map.put(21, "Forward 6 Colors WH");
        map.put(22, "Backward 6 Colors WH");
        map.put(23, "Forward Trailing 7 Colors");
        map.put(24, "Backward Trailing 7 Colors");
        map.put(25, "Forward Trailing RD");
        map.put(26, "Backward Trailing RD");
        map.put(27, "Forward Trailing GN");
        map.put(28, "Backward Trailing GN");
        map.put(29, "Forward Trailing BU");
        map.put(30, "Backward Trailing BU");
        map.put(31, "Forward Trailing YE");
        map.put(32, "Backward Trailing YE");
        map.put(33, "Forward Trailing CN");
        map.put(34, "Backward Trailing CN");
        map.put(35, "Forward Trailing VT");
        map.put(36, "Backward Trailing VT");
        map.put(37, "Forward Trailing WH");
        map.put(38, "Backward Trailing WH");
        map.put(39, "Forward Streaming 7 Colors");
        map.put(40, "Backward Streaming 7 Colors");
        map.put(41, "Forward Streaming RD/GN/BU");
        map.put(42, "Backward Streaming RD/GN/BU");
        map.put(43, "Forward Streaming YE/CN/VT");
        map.put(44, "Backward Streaming YE/CN/VT");
        map.put(45, "Forward Streaming RD/GN");
        map.put(46, "Backward Streaming RD/GN");
        map.put(47, "Forward Streaming GN/BU");
        map.put(48, "Backward Streaming GN/BU");
        map.put(49, "Forward Streaming YE/BU");
        map.put(50, "Backward Streaming YE/BU");
        map.put(51, "Forward Streaming YE/CN");
        map.put(52, "Backward Streaming YE/CN");
        map.put(53, "Forward Streaming CN/VT");
        map.put(54, "Backward Streaming CN/VT");
        map.put(55, "Forward Streaming BK/WH");
        map.put(56, "Backward Streaming BK/WH");
        map.put(57, "Open Curtain 7 Colors");
        map.put(58, "Close Curtain 7 Colors");
        map.put(59, "Open Curtain RD/GN/BU");
        map.put(60, "Close Curtain RD/GN/BU");
        map.put(61, "Open Curtain YE/CN/VT");
        map.put(62, "Close Curtain YE/CN/VT");
        map.put(63, "Forward Follow Spot 7 Colors");
        map.put(64, "Backward Follow Spot 7 Colors");
        map.put(65, "Forward Follow Spot RD/GN/BU");
        map.put(66, "Backward Follow Spot RD/GN/BU");
        map.put(67, "Forward Follow Spot YE/CN/VT");
        map.put(68, "Backward Follow Spot YE/CN/VT");
        map.put(69, "Forward Flutter 7 Colors");
        map.put(70, "Backward Flutter 7 Colors");
        map.put(71, "Forward Flutter RD/GN/BU");
        map.put(72, "Backward Flutter RD/GN/BU");
        map.put(73, "Forward Flutter YE/CN/VT");
        map.put(74, "Backward Flutter YE/CN/VT");
        map.put(75, "Hop 7 Colors");
        map.put(76, "Hop RD/GN/BU");
        map.put(77, "Hop RD/GN/BU");
        map.put(78, "Strobe 7 Colors");
        map.put(79, "Strobe RD/GN/BU");
        map.put(80, "Strobe YE/CN/VT");
        map.put(81, "Gradual 7 Colors");
        map.put(82, "Gradual RD/E");
        map.put(83, "Gradual RD/VT");
        map.put(84, "Gradual GN/CN");
        map.put(85, "Gradual GN/YE");
        map.put(86, "Gradual BU/VT");
        map.put(87, "Close Curtain RD");
        map.put(88, "Close Curtain GN");
        map.put(89, "Close Curtain BU");
        map.put(90, "Close Curtain YE");
        map.put(91, "Close Curtain CN");
        map.put(92, "Close Curtain VT");
        map.put(93, "Close Curtain WH");
        map.put(94, "Open Curtain RD");
        map.put(95, "Open Curtain GN");
        map.put(96, "Open Curtain BU");
        map.put(97, "Open Curtain YE");
        map.put(98, "Open Curtain CN");
        map.put(99, "Open Curtain VT");
        map.put(100, "Open Curtain WH");
        map.put(101, "Horse Race RD");
        map.put(102, "Horse Race GN");
        map.put(103, "Horse Race BU");
        map.put(104, "Horse Race YE");
        map.put(105, "Horse Race CN");
        map.put(106, "Horse Race VT");
        map.put(107, "Horse Race WH");
        map.put(108, "Forward Run RD");
        map.put(109, "Backward Run RD");
        map.put(110, "Forward Run GN");
        map.put(111, "Backward Run GN");
        map.put(112, "Forward Run BU");
        map.put(113, "Backward Run BU");
        map.put(114, "Forward Run YE");
        map.put(115, "Backward Run YE");
        map.put(116, "Forward Run CN");
        map.put(117, "Backward Run CN");
        map.put(118, "Forward Run VT");
        map.put(119, "Backward Run VT");
        map.put(120, "Forward Run WH");
        map.put(121, "Backward Run WH");
        map.put(122, "Forward Run 7 Colors");
        map.put(123, "Backward Run 7 Colors");
        map.put(124, "Forward Run RD/GN/BU");
        map.put(125, "Backward Run RD/GN/BU");
        map.put(126, "Forward Run YE/CN/VT");
        map.put(127, "Backward Run YE/CN/VT");
        map.put(128, "Forward Run BU/YE/VT");
        map.put(129, "Forward Run GN/BU/YE");
        map.put(130, "Backward Run BU/YE/VT");
        map.put(131, "Forward Run RD/ON/WH");
        map.put(132, "Backward Run RD/ON/WH");
        map.put(133, "Forward Run GN ON RD");
        map.put(134, "Backward Run GN ON RD");
        map.put(135, "Forward Run BU ON GN");
        map.put(136, "Backward Run BU ON GN");
        map.put(137, "Forward Run YE ON BU");
        map.put(138, "Backward Run YE ON BU");
        map.put(139, "Forward Run CN ON YE");
        map.put(140, "Backward Run CN ON YE");
        map.put(141, "Forward Run VT ON CN");
        map.put(142, "Backward Run VT ON CN");
        map.put(143, "Forward Run WH ON VT");
        map.put(144, "Backward Run WH ON VT");
        map.put(145, "Forward Run WH ON RD");
        map.put(146, "Backward Run WH ON RD");
        map.put(147, "Forward Run 7 COLOR ON RD");
        map.put(148, "Backward Run 7 COLOR ON RD");
        map.put(149, "Forward Run 7 COLOR ON GN");
        map.put(150, "Backward Run 7 COLOR ON GN");
        map.put(151, "Forward Run 7 COLOR ON BU");
        map.put(152, "Backward Run 7 COLOR ON BU");
        map.put(153, "Forward Run 7 COLOR ON YE");
        map.put(154, "Backward Run 7 COLOR ON YE");
        map.put(155, "Forward Run 7 COLOR ON CN");
        map.put(156, "Backward Run 7 COLOR ON CN");
        map.put(157, "Forward Run 7 COLOR ON VT");
        map.put(158, "Backward Run 7 COLOR ON VT");
        map.put(159, "Forward Run 7 COLOR ON WH");
        map.put(160, "Backward Run 7 COLOR ON WH");
        map.put(161, "Forward Flow WH RD WH");
        map.put(162, "Backward Flow WH RD WH");
        map.put(163, "Forward Flow WH GN WH");
        map.put(164, "Backward Flow WH GN WH");
        map.put(165, "Forward Flow WH BU WH");
        map.put(166, "Backward Flow WH BU WH");
        map.put(167, "Forward Flow WH YE WH");
        map.put(168, "Backward Flow WH YE WH");
        map.put(169, "Forward Flow WH CN WH");
        map.put(170, "Backward Flow WH CN WH");
        map.put(171, "Forward Flow WH VT WH");
        map.put(172, "Backward Flow WH VT WH");
        map.put(173, "Forward Flow RD WH RD");
        map.put(174, "Backward Flow RD WH RD");
        map.put(175, "Forward Flow GN WH GN");
        map.put(176, "Backward Flow GN WH GN");
        map.put(177, "Forward Flow BU WH BU");
        map.put(178, "Backward Flow BU WH BU");
        map.put(179, "Forward Flow YE WH YE");
        map.put(180, "Backward Flow YE WH YE");
        map.put(181, "Forward Flow CN WH CN");
        map.put(182, "Backward Flow CN WH CN");
        map.put(183, "Forward Flow VT WH VT");
        map.put(184, "Backward Flow VT WH VT");
        map.put(185, "Forward Run GN ON BU");
        map.put(186, "Backward Run GN ON BU");
        map.put(187, "Forward Run GN ON RD");
        map.put(188, "Backward Run GN ON RD");
        map.put(189, "Forward Run RD ON BU");
        map.put(190, "Backward Run RD ON BU");
        map.put(191, "Forward Run CN ON YE");
        map.put(192, "Backward Run CN ON YE");
        map.put(193, "Forward Run YE ON VT");
        map.put(194, "Backward Run YE ON VT");
        map.put(195, "Forward Run WH ON YE");
        map.put(196, "Backward Run WH ON YE");
        map.put(197, "Forward Run YE ON WH");
        map.put(198, "Backward Run YE ON WH");
        map.put(199, "Forward Swab 7 COLORS");
        map.put(200, "Backward Swab 7 COLORS");
        map.put(201, "Forward Swab RD GN BU");
        map.put(202, "Backward Swab RD GN BU");
        map.put(203, "Forward Swab YE CN VT");
        map.put(204, "Backward Swab YE CN VT");
        map.put(205, "Open Curtain Swab 7 COLORS");
        map.put(206, "Close Curtain Swab 7 COLORS");
        map.put(207, "Open Curtain Swab R G B");
        map.put(208, "Close Curtain Swab R G B");
        map.put(209, "Open Curtain Swab Y C P");
        map.put(210, "Close Curtain Swab Y C P");
        NAMES = Collections.unmodifiableMap(map);
    }

    private DmxModes() {
    }
}
